### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Markel** [MarkelFe/metacritic-crawler#31]
This is a list of things to do, it can be useful if you want to find something to improve in the project. You can leave your ideas in the comments.

![Easy](https://img.shields.io/badge/-easy-brightgreen.svg?style=for-the-badge)
* [ ] Implement [tqdm.close()](https://tqdm.github.io/docs/tqdm/#close)

![Medium](https://img.shields.io/badge/-medium-orange.svg?style=for-the-badge)
* [ ] Introduce 9b01f1a but for `-s CLOSESPIDER_PAGECOUNT`
* [ ] #24 - Platform problems
* [ ] Delete the double loading bar on analyze.py

![Hard](https://img.shields.io/badge/-hard-red.svg?style=for-the-badge)
* [ ] #5 - A launcher
    * [ ] Basic functionality
    * [ ] Multiple loading bars (you may want to check [the position parameter](https://tqdm.github.io/docs/tqdm/#tqdm))
* [ ] Allow other dates
    * [ ] Last 90 days
    * [ ] By year
* [ ] Other categories
